name: Test fetching secrets

on:
  push:
    branches:
      - main

# permissions:
#   contents: write

jobs:
  build:
    name: Test Fetch
    runs-on: ubuntu-latest
    steps:
      - name: Test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CRATE_TOKEN: ${{ secrets.RUST_CRATE_SECRET }}
        run: |
          echo "Show secret object: ${{ secrets }}"
          echo "Show github token from env: $GH_TOKEN"
          echo "Show crate token: $CRATE_TOKEN"
          echo "Show crate token from secret: ${{ secrets.RUST_CRATE_SECRET }}"
          python -c "import os; print(os.environ['CRATE_TOKEN'])"
